# golangci-lint v2 configuration for jp-go-resilience
version: "2"

run:
  timeout: 5m

linters:
  default: standard

  exclusions:
    rules:
      # Tests may skip error checks for brevity
      - path: _test\.go
        linters:
          - errcheck
